# Build a development Flatpak build
name: Build Flatpak
on:
  # Runs on push in repository or pull requests
  push:
  pull_request:

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    # We run the job three times with different platforms enabled
    strategy:
      fail-fast: false
      matrix:
        platforms: [Twitter, Mastodon, Full]
    name: "${{ matrix.platforms }} Build"
    env:
      BACKENDS: ${{ matrix.platforms }}
      TWITTER_OAUTH_KEY: ${{ secrets.TWITTER_OAUTH_KEY }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Run Flatpak Builder
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          bundle: "Cawbird-Devel-${{ matrix.platforms }}.flatpak"
          manifest-path: uk.co.ibboard.Cawbird.Devel.json
          repository-name: gnome-nightly
          repository-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
          run-tests: true
          cache-key: flatpak-builder-${{ matrix.platforms }}-${{ github.sha }}
