# Build a development Flatpak build
name: Build Flatpak
on:
  # Runs on push in repository or pull requests
  push:
  pull_request:

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-nightly
      options: --privileged
    # We run the job three times with different platforms enabled
    strategy:
      fail-fast: false
      matrix:
        # Disable "full" build, because it is currently identical to "Mastodon"
        #platforms: [Mastodon, Full]
        platforms: [Mastodon]
        arch: [x86_64, aarch64]
    name: "${{ matrix.platforms }} Build - ${{ matrix.arch }}"
    env:
      BACKENDS: ${{ matrix.platforms }}
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          submodules: true
      # Installing docker for setup-qemu-action
      - name: Install deps
        run: |
          dnf -y install docker
      # Using QEMU to cross-compile for ARM
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - name: Run Flatpak Builder
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
        with:
          arch: ${{ matrix.arch }}
          bundle: "Cawbird-Devel-${{ matrix.platforms }}.flatpak"
          manifest-path: build-aux/Flatpak/uk.co.ibboard.Cawbird.Devel.json
          repository-name: gnome-nightly
          repository-url: https://nightly.gnome.org/gnome-nightly.flatpakrepo
          run-tests: true
          cache-key: flatpak-builder-${{ matrix.platforms }}-${{ github.sha }}
